name: bank

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: build banking
          working-directory: banking
          run: |
            cmake -S. -B_built
            cmake --build _built
